export const SET_PAGE_CONTENT = 'SET_PAGE_CONTENT';
export const SET_NAVBAR_ACTIVEITEM = 'SET_NAVBAR_ACTIVEITEM';
export const ADD_BAG_ITEM = "ADD_BAG_ITEM";
export const REMOVE_BAG_ITEM = "REMOVE_BAG_ITEM";
export const SET_POKE_DETAIL = "SET_POKE_DETAIL";
export const SET_POKE_SHINY = "SET_POKE_SHINY";

